open Drcpcheck_core.Checker.ProofFacts
open Drcpcheck_core.Checker
open Angstrom
open Big_int_Z

type atom_definition = { id : int; atomic : coq_BoundAtomic }

type inference = {
  constraint_id : big_int;
  premises : int list;
  consequent : int option;
  generated_by : big_int list;
  label : string;
}

type deduction = {
  constraint_id : big_int;
  premises : int list;
  sequence : big_int list;
}

type step =
  | Inference of inference
  | Deduction of deduction
  | AtomDefinition of atom_definition

(* let ( <?> ) p l = *)
(*   let* remaining = available in *)
(*   let remaining = Int.min remaining 20 in *)
(*   let* s = peek_string remaining in *)
(*   p <?> Printf.sprintf "%s, got: [%s]" l s *)

let ws =
  skip_while (function ' ' | '\t' -> true | _ -> false) <?> "whitespace"

let ws_with_new_line =
  skip_while (function ' ' | '\t' -> true | '\n' -> true | _ -> false)
  <?> "whitespace separator with newline"

let ws_sep =
  take_while1 (function ' ' | '\t' -> true | _ -> false)
  <?> "expected whitespace seperator"

let eol = ws *> char '\n' <* ws_with_new_line <?> "expected newline"

(* Parses Ocaml integers *)
let is_digit = function '0' .. '9' -> true | _ -> false
let is_non_zero_digit = function '1' .. '9' -> true | _ -> false

let assrt p =
  peek_char >>= (function Some c when p c -> return () | _ -> fail "!")

let num first_ok =
  let negb =
    peek_char >>= function
    | Some '-' -> advance 1 *> return true
    | Some '+' -> advance 1 *> return false
    | Some c when first_ok c -> return false
    | _ -> fail "Sign or non-zero digit expected" in
  lift2 (fun negb digits -> (negb, digits)) negb (take_while1 is_digit)

let atomic_code =
  num is_non_zero_digit >>= fun (negb, digits) ->
  let i = int_of_string digits in
  return (if negb then -i else i)
  <?> "expected atomic/constraint id"

(* Parser for a variable name. *)
let is_letter c = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')

let ident =
  assrt (fun c -> is_letter c || c = '_') >>= fun () ->
  take_while (fun c -> is_letter c || is_digit c || c = '_') >>= fun rest ->
  return rest <?> "expected variable identifier"

(* Parser for big-integers. *)
let big_integer =
  num is_digit >>= fun (negb, digits) ->
  let bi = big_int_of_string digits in
  return (if negb then Big_int_Z.sub_big_int Big_int_Z.zero_big_int bi else bi)
  <?> "expected big integer"

let cmp =
  choice
    [
      string ">=" *> return Coq_greater_equal <?> "greater equal";
      string "<=" *> return Coq_less_equal <?> "less equal";
      string "==" *> return Coq_equal <?> "equal";
      string "!=" *> return Coq_not_equal <?> "not equal";
    ]
  <?> "expected comparator"

let atom =
  char '['
  *> lift3
       (fun var_name comparator value ->
         (var_name, { atm_cmp = comparator; atm_val = value }))
       ident
       (ws_sep *> cmp <* ws_sep)
       big_integer
  <* char ']' <?> "expected atomic"

let atom_definition =
  char 'a' *> ws_sep
  *> lift2
       (fun atom_id atomic -> { id = atom_id; atomic })
       atomic_code (ws_sep *> atom)
  <* eol <?> "expected atomic definition line"

let inference_rule =
  ident

let premises = many (atomic_code <* ws_sep) <* char '0'

let inference_args =
  let generated_by =
    option [] (ws_sep *> string "c:" *> big_integer >>| fun id -> [ id ])
    <?> "generated by"
  in
  let label = ws_sep *> string "l:" *> inference_rule <?> "inference label" in
  lift2 (fun gb lbl -> (gb, lbl)) generated_by label
  <|> lift2 (fun lbl gb -> (gb, lbl)) label generated_by

let inference_line =
  char 'i' *> ws_sep *> (big_integer <* ws_sep) >>= fun constraint_id ->
  premises >>= fun premises ->
  option None (ws_sep *> atomic_code >>| fun id -> Some id)
  >>= fun consequent ->
  inference_args >>= fun (generated_by, label) ->
  return { constraint_id; premises; consequent; generated_by; label }
  <* eol <?> "inference line"

let deduction_line =
  char 'n' *> ws_sep
  *> lift3
       (fun id premises sequence -> { constraint_id = id; premises; sequence })
       (big_integer <* ws_sep) premises
       (many (ws_sep *> big_integer))
  <* eol <?> "deduction line"

let proof_line =
  ws_with_new_line *> peek_char_fail >>= function
  | 'a' -> atom_definition >>| fun def -> AtomDefinition def
  | 'i' -> inference_line >>| fun inf -> Inference inf
  | 'n' -> deduction_line >>| fun deduction -> Deduction deduction
  | _ -> fail "Unknown proof line"

type conclusion = Unsat | DualBound of int

let conclusion_line =
  char 'c' *> ws_sep
  *> (string "UNSAT" *> return Unsat
     <?> "unsat conclusion"
     <|> (atomic_code
         >>| (fun code -> DualBound code)
         <?> "dual bound conclusion"))
  <* ws_with_new_line <?> "conclusion line"

let proof =
  many proof_line >>= fun steps ->
  conclusion_line >>= fun conclusion -> return (steps, conclusion)

module IntMap = Map.Make (Int)

exception DoublyDefinedAtomicError
exception UndefinedAtomic of int

let negate_atomic = function
  | name, atomic -> (
      match atomic.atm_cmp with
      | Coq_less_equal ->
          ( name,
            {
              atm_cmp = Coq_greater_equal;
              atm_val = succ_big_int atomic.atm_val;
            } )
      | Coq_greater_equal ->
          ( name,
            { atm_cmp = Coq_less_equal; atm_val = pred_big_int atomic.atm_val }
          )
      | Coq_equal ->
          (name, { atm_cmp = Coq_not_equal; atm_val = atomic.atm_val })
      | Coq_not_equal ->
          (name, { atm_cmp = Coq_equal; atm_val = atomic.atm_val }))

type atomic_map = coq_BoundAtomic IntMap.t

let resolve_atomic_id atomics id =
  let positive = IntMap.find_opt id atomics in
  let negative = Option.map negate_atomic (IntMap.find_opt (-id) atomics) in
  match (positive, negative) with
  | Some a1, Some a2 -> if a1 == a2 then a1 else raise DoublyDefinedAtomicError
  | Some a1, None -> a1
  | None, Some a1 -> a1
  | None, None -> raise (UndefinedAtomic id)

let resolve_atomic_ids atomics ids = List.map (resolve_atomic_id atomics) ids

let convert_inference (atomics : atomic_map) (inference : inference) :
    indexedInference =
  {
    iinf_index = inference.constraint_id;
    iinf_fact =
      {
        i_premises = resolve_atomic_ids atomics inference.premises;
        i_consequent =
          Option.map (resolve_atomic_id atomics) inference.consequent;
      };
    iinf_hint = inference.generated_by;
    iinf_rule = inference.label;
  }

exception IncompleteProofError

let rec convert_proof_stage (steps : step list) (atomics : atomic_map)
    (acc : indexedInference list) :
    coq_BoundAtomic IntMap.t * proofStage option * step list =
  match steps with
  | [] -> (atomics, None, [])
  | AtomDefinition def :: tail ->
      convert_proof_stage tail (IntMap.add def.id def.atomic atomics) acc
  | Inference inf :: tail ->
      convert_proof_stage tail atomics (convert_inference atomics inf :: acc)
  | Deduction deduction :: tail ->
      ( atomics,
        Some
          {
            s_inferences = List.rev acc;
            s_conclusion =
              {
                i_premises = resolve_atomic_ids atomics deduction.premises;
                i_consequent = None;
              };
            s_chain = deduction.sequence;
            s_conclusion_index = deduction.constraint_id;
          },
        tail )

let rec convert_steps_to_proof (steps : step list) (atomics : atomic_map)
    (acc : proofStage list) : proofStage list * atomic_map =
  match steps with
  | [] -> (List.rev acc, atomics)
  | head :: tail -> (
      match convert_proof_stage (head :: tail) atomics [] with
      | new_atomics, Some stage, rest ->
          convert_steps_to_proof rest new_atomics (stage :: acc)
      | new_atomics, None, [] -> (acc, new_atomics)
      | _, None, _ -> raise IncompleteProofError)

exception ParseError of string

let parse_proof (source : string) : proofStage list * coq_ProofFact =
  match parse_string ~consume:All proof source with
  | Ok (steps, conclusion) ->
      let proof, atomics = convert_steps_to_proof steps IntMap.empty [] in
      let conclusion_fact =
        match conclusion with
        | Unsat -> { i_premises = []; i_consequent = None }
        | DualBound code ->
            {
              i_premises = [ resolve_atomic_id atomics (-code) ];
              i_consequent = None;
            }
      in
      (proof, conclusion_fact)
  | Error e -> raise (ParseError e)
