(rule
 (targets libfzn_drcp_check_parsing.a dllfzn_drcp_check_parsing.so)
 (deps (glob_files *.rs))
 (action
  (progn
   (run sh -c "cd %{project_root}/../../lib/parsing && cargo build --release")
   (run sh -c
     "mv %{project_root}/../../lib/parsing/target/release/libfzn_drcp_check_parsing.so ./dllfzn_drcp_check_parsing.so 2> /dev/null || \
      mv %{project_root}/../../lib/parsing/target/release/libfzn_drcp_check_parsing.dylib ./dllfzn_drcp_check_parsing.so")
   (run mv %{project_root}/../../lib/parsing/target/release/libfzn_drcp_check_parsing.a libfzn_drcp_check_parsing.a))))

(library
 (name fzn_drcp_check_parsing)
 (public_name fzn_drcp_check_parsing)
 (foreign_archives fzn_drcp_check_parsing)
 (c_library_flags
  (-lpthread -lc -lm)))
