(* Generated by ocaml-rs *)

open! Bigarray

(* file: lib.rs *)

type comparator = Leq | Geq | Eq | Ne
type atomic = { variable: string; comparator: comparator; value: int }
type conclusion = Unsat | Optimal of atomic
type inference = { premises: atomic list; conclusion: atomic }
type step = Inference of inference | Nogood of atomic list
type proof = { steps: step list; conclusion: conclusion }
external parse_proof: string -> proof = "parse_proof"
