(lang dune 3.16)

(name fzn_drcp_check)

(generate_opam_files true)

(source
 (github ConSol-Lab/fzn-drcp-check))

(authors "Maarten Flippo" "Konstantin Sidorov")

(maintainers "Maarten Flippo" "Konstantin Sidorov")

(license MIT)

(documentation https://url/to/documentation)

(package
 (name fzn_drcp_check)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml dune)
 (tags
  (topics "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
